language: c
os: linux
dist: trusty
sudo: required
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - trusty
    packages:
      - autoconf
      - automake
      - autotools-dev
      - build-essential
      - debhelper
      - dh-autoreconf
      - dpkg-dev
      - gnome-doc-utils
      - gnome-doc-utils
      - imagemagick
      - intltool
      - libexiv2-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblircclient-dev
      - liblua5.1-0-dev
      - libtiff-dev
      - libtool
script: (CFLAGS= ./autogen.sh) && make
