name: Geeqie x86_64 AppImage build
run-name: ${{ github.actor }} is running Geeqie x86_64 AppImage build
on: [push]
jobs:
  Build-AppImage:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential libgtk-3-dev libgtk-3-bin
    - run: sudo apt-get install evince
    - run: sudo apt-get install libarchive-dev
    - run: sudo apt-get install libchamplain-0.12-dev libchamplain-gtk-0.12-dev
    - run: sudo apt-get install libffmpegthumbnailer-dev
    - run: sudo apt-get install libgexiv2-dev
    - run: sudo apt-get install libgspell-1-dev
    - run: sudo apt-get install libheif-dev
    - run: sudo apt-get install liblua5.3-dev
    - run: sudo apt-get install libpoppler-glib-dev
    - run: sudo apt-get install libraw-dev libomp-dev
    - run: sudo apt-get install libwebp7
    - run: sudo apt-get install libwebp-dev
    - run: sudo apt-get install webp-pixbuf-loader
    - run: sudo apt-get install pandoc
    - run: sudo apt-get install gettext
    - run: sudo apt-get install yelp-tools

    - uses: actions/checkout@v3
    - run: git fetch --tags --force
    - run: git fetch --depth=1000000
    - uses: actions/setup-python@v4
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build
        options: --verbose
        meson-version: 1.0.1

    - name: build
      run: DESTDIR=/home/runner/work/geeqie/geeqie/AppDir ninja -C build install
    - name: build AppImage
      uses: AppImageCrafters/build-appimage-action@master
      with:
        recipe: AppImageBuilder-x86_64.yml

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
         allowUpdates: true
         tag: continuous
         name: Continuous build
         prerelease: true
         artifacts: "Geeqie-latest-x86_64.AppImage"

    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: logs-all-build-appimage
        path: /home/runner/work/geeqie/geeqie/build/meson-logs/*.txt
        retention-days: 5
