name: Geeqie minimal x86_64 AppImage build
run-name: ${{ github.actor }} is running Geeqie minimal x86_64 AppImage build
on: [push]
jobs:
  Build-AppImage:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential libgtk-3-dev libgtk-3-bin
    - run: sudo apt-get install gettext

    - uses: actions/checkout@v3
    - run: git fetch --tags --force
    - uses: actions/setup-python@v4
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build
        setup-options: -Darchive=disabled -Dcms=disabled -Ddevel=disabled -Ddoxygen=disabled -Ddjvu=disabled -Devince=disabled -Dexecinfo=disabled -Dexiv2=disabled -Dgit=disabled -Dgps-map=disabled -Dheif=disabled -Dj2k=disabled -Djpeg=disabled -Djpegxl=disabled -Dlibraw=disabled -Dlua=disabled -Dpandoc=disabled -Dpdf=disabled -Dspell=disabled -Dtiff=disabled -Dvideothumbnailer=disabled -Dwebp=disabled -Dyelp-build=disabled
        options: --verbose
        meson-version: 1.0.1

    - name: build
      run: DESTDIR=/home/runner/work/geeqie/geeqie/AppDir ninja -C build install
    - name: build AppImage
      uses: AppImageCrafters/build-appimage-action@master
      with:
        recipe: AppImageBuilderMinimal-x86_64.yml

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
         allowUpdates: true
         tag: continuous
         name: Continuous build
         prerelease: true
         artifacts: "Geeqie-minimal-latest-x86_64.AppImage"

    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: logs-all-build-appimage
        path: /home/runner/work/geeqie/geeqie/build/meson-logs/*.txt
        retention-days: 5
