name: Geeqie check build
run-name: ${{ github.actor }} is running Geeqie check build
on: [push]
jobs:
  Check-Build-No-Options:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install build-essential libgtk-3-dev
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        meson-version: 0.56.2

  Check-Build-Most-Options:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install build-essential libgtk-3-dev
    - run: sudo apt-get install evince
    - run: sudo apt-get install libarchive-dev
    - run: sudo apt-get install libchamplain-0.12-dev libchamplain-gtk-0.12-dev
    #~ - run: sudo apt-get install libffmpegthumbnailer-dev
    - run: sudo apt-get install libgexiv2-dev
    - run: sudo apt-get install libgspell-1-dev
    - run: sudo apt-get install libheif-dev
    - run: sudo apt-get install liblua5.3-dev
    - run: sudo apt-get install libpoppler-glib-dev
    - run: sudo apt-get install libraw-dev libomp-dev
    - run: sudo apt-get install pandoc
    #~ - run: sudo apt-get install yelp-tools
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        meson-version: 0.56.2
