name: Geeqie check build
run-name: ${{ github.actor }} is running Geeqie check build
on: [push, pull_request]
jobs:
  Check-Build-No-Options:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential libgtk-3-dev libgtk-3-bin
    - run: sudo apt-get install shellcheck
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: sudo apt-get install xvfb
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        setup-options: -Darchive=disabled -Dcms=disabled -Ddevel=disabled -Ddoxygen=disabled -Ddjvu=disabled -Devince=disabled -Dexecinfo=disabled -Dexiv2=disabled -Dgit=disabled -Dgps-map=disabled -Dheif=disabled -Dj2k=disabled -Djpeg=disabled -Djpegxl=disabled -Dlibraw=disabled -Dlua=disabled -Dpandoc=disabled -Dpdf=disabled -Dspell=disabled -Dtiff=disabled -Dvideothumbnailer=disabled -Dyelp-build=disabled
        options: --verbose
        meson-version: 0.56.2
    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: logs-all
        path: /home/runner/work/geeqie/geeqie/build/meson-logs/*.txt
        retention-days: 5

  Check-Build-Most-Options:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential libgtk-3-dev libgtk-3-bin
    - run: sudo apt-get install shellcheck
    - run: sudo apt-get install evince
    - run: sudo apt-get install libarchive-dev
    - run: sudo apt-get install libchamplain-0.12-dev libchamplain-gtk-0.12-dev
    #~ - run: sudo apt-get install libffmpegthumbnailer-dev
    - run: sudo apt-get install libgexiv2-dev
    - run: sudo apt-get install libgspell-1-dev
    - run: sudo apt-get install libheif-dev
    - run: sudo apt-get install liblua5.3-dev
    - run: sudo apt-get install libpoppler-glib-dev
    - run: sudo apt-get install libraw-dev libomp-dev
    - run: sudo apt-get install pandoc
    #~ - run: sudo apt-get install yelp-tools
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: sudo apt-get install xvfb
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        setup-options: -Ddevel=enabled
        options: --verbose
        meson-version: 0.56.2
    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: logs-all
        path: /home/runner/work/geeqie/geeqie/build/meson-logs/*.txt
        retention-days: 5
